semi: true
singleQuote: true
tabWidth: 2
useTabs: false
plugins:
  - '@trivago/prettier-plugin-sort-imports'
  - 'prettier-plugin-tailwindcss'
importOrder:
  - '^node:(.*)$'
  - '<THIRD_PARTY_MODULES>'
  - '^@/components/ui/(.*)$'
  - '^@/(.*)$'
  - '^[./]'
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrderGroupNamespaceSpecifiers: true
importOrderCaseInsensitive: true
